---
title:  "CHIKV 28dpi FcR expression"
author: "Ryan Sheridan"
date:   "`r Sys.Date()`"
output: 
  html_document:
    toc:       true
    toc_float: true
    toc_depth: 3
    theme:     cosmo
    highlight: kate
params:
  
  unenr_dir:    "results/2021-11-05"      # Directory containing unenriched data
  enr_dir:      "results/2022-02-03"      # Directory containing CHIKV-enriched data
  template_dir: "src"                     # Directory containing Rmd templates
  table_dir:    "tables"                  # Directory to write tables
  overwrite:    false                     # Should tables be overwritten if they already exist?
  so_dir:       "~/Dropbox/Ryan/Projects" # Directory to write Seurat objects
  metrics:      "count_metrics.csv"       # Cell Ranger metrics
  gene_min:     250                       # Min number of detected genes per cell
  gene_max:     5500                      # Max number of detected genes per cell
  mito_max:     30                        # Max percentage mito reads per cells
  rm_doublets:  true                      # Should doublets be removed using DoubletFinder?
  type_res:     5                         # Clustering resolution for annotating cell types
  mac_res:      1                         # Clustering resolution for annotating macrophages
  lec_res:      5                         # Clustering resolution for annotating LECs
  fib_res:      5                         # Clustering resolution for annotating fibroblasts/stromal cells
  tm:           "28dpi"                   # Label for time point
  samples:
    - "U1"
    - "U2"
    - "U3"
    - "C1"
    - "C2"
    - "C3"
editor_options: 
  chunk_output_type: inline
---

<br>

```{r "setup", include = FALSE}

# Default chunk options
knitr::opts_chunk$set(
  message = FALSE,
  warning = FALSE,
  echo    = FALSE,
  dpi     = 600
)

# Adjust directory paths based on user input
enr_dir   <- params$enr_dir
unenr_dir <- params$unenr_dir

if (enr_dir == "") enr_dir <- unenr_dir

knitr::knit(here::here(unenr_dir, "Rmds/setup.Rmd"), output = "")

other_pkgs <- c(
  "clusterProfiler",
  "enrichplot",
  "msigdbr",
  "DOSE",
  "biomaRt",
  "org.Mm.eg.db",
  "qs"
)

purrr::walk(other_pkgs, library, character.only = TRUE)

# Load objects
create_so <- !file.exists(file.path(so_dir, "so_int.qs"))

```

```{r "culemann gene lists"}

# Gene lists from Culemann et al.
culemann_genes <- list(
  mock  = here("ref/2019_Culemann/table_s1.txt"),
  CHIKV = here("ref/2019_Culemann/table_s2.txt")
)

culemann_genes <- culemann_genes %>%
  map(~ {
    read_delim(
      file   = .x,
      delim  = " ",
      locale = locale(decimal_mark = ",")
    )
  })

feat_key <- list(
  mock = c(
    "0" = "AQP1_interstitial",
    "2" = "RELMa_interstitial",
    "3" = "CX3CR1_lining",
    "1" = "MHCII_interstitial",
    "4" = "STMN1_proliferating",  # weak non-specific signal
    "5" = "ACP5_osteoclast"
  ),
  CHIKV = c(
    "1" = "CX3CR1_lining",
    "2" = "RELMa_interstitial",
    "0" = "CCR2_IL1B_infiltrating",
    "4" = "CCR2_ARG1_infiltrating",
    "3" = "MHCII_interstitial",
    "6" = "STMN1_proliferating",
    "5" = "MHCII_DCs"
  )
)

culemann_genes <- culemann_genes %>%
  imap(~ {
    .x %>%
      mutate(cluster = feat_key[[.y]][as.character(cluster)])
  })

feat_key <- list(
  mock  = unname(feat_key$mock[1:3]),
  CHIKV = unname(grep("infiltrating$", feat_key$CHIKV, value = TRUE))
)

feat_lvls <- unlist(feat_key, use.names = FALSE)



# plt_feats <- feats %>%
#   imap(~ c(.y, .x))

# data.frame of features that can be used with clustifyr
# feats_df <- tibble(feats, key = names(feats)) %>%
#   unnest(feats) %>%
#   group_by(key) %>%
#   mutate(idx = row_number()) %>%
#   ungroup() %>%
#   pivot_wider(
#     names_from = key,
#     values_from = feats,
#     values_fill = NA
#   ) %>%
#   dplyr::select(-idx)

### MEAN SIGNAL TEST ###
# See only minor differences when compared with module scores
# and signals show similar trends
#
# mn_signal <- feats %>%
#   imap(~ {
#     so_int %>%
#       FetchData(c("sample", "cell_type", .x)) %>%
#       as_tibble(rownames = ".cell_id") %>%
#       pivot_longer(any_of(.x)) %>%
#       group_by(.cell_id) %>%
#       summarize(!!sym(.y) := mean(value))
#   }) %>%
#   reduce(left_join, by = ".cell_id") %>%
#   column_to_rownames(".cell_id")
# 
# x <- so_int %>%
#   AddMetaData(mn_signal)
# 
# names(feats) %>%
#   map(~ {
#     x %>%
#       plot_features(
#         feature     = .x,
#         plot_colors = c("blue", "white", "red"),
#         size        = 0.5
#       ) +
#       theme(aspect.ratio = 0.9)
#   }) %>%
#   plot_grid(
#     plotlist = .,
#     align    = "vh",
#     axis     = "trbl"
#   )
# 
# so_int@meta.data %>%
#   pivot_longer(all_of(names(feats))) %>%
#   ggplot(aes(mac_type, value, fill = mac_type)) +
#   geom_boxplot() +
#   facet_wrap(~ name, scales = "free_y")

# x <- so_treats %>%
#   imap(~ {
#     fts   <- feats[[.y]]
#     lvls  <- names(fts)
#     clmns <- set_names(str_c(lvls, seq_along(lvls)), lvls)
#     
#     .x %>%
#       mutate_meta(dplyr::select, -any_of(lvls)) %>%
#       AddModuleScore(
#         fts,
#         name = lvls,
#         seed = 42,
#         ctrl = 35
#       ) %>%
#       mutate_meta(rename, !!!syms(clmns))
#   })
# 
# names(feats$CHIKV) %>%
#   map(~ {
#     x$CHIKV %>%
#       # subset(treatment == "CHIKV") %>%
#       plot_features(feature = .x, size = 0.5) +
#       facet_wrap(~ treatment) +
#       theme(aspect.ratio = 1)
#   }) %>%
#   plot_grid(plotlist = .)
# 
# Fraction CHIKV
# x$CHIKV@meta.data %>%
#   group_by(!!sym(int_clst_clmn)) %>%
#   mutate(frac_chikv = length(treatment[treatment == "CHIKV"]) / n()) %>%
#   plot_features(feature = "frac_chikv")

```

```{r "theme"}

# ggplot2 themes
txt_pt1  <- 10
txt_pt2  <- 12
ttl_pt1  <- 14
ttl_pt2  <- 16
ln_pt    <- 0.5
ln_col   <- "grey85"
cir_size <- 3.5
sqr_size <- 4

txt_theme_1 <- theme(
  strip.text  = element_text(size = ttl_pt1),
  legend.text = element_text(size = txt_pt1),
  axis.title  = element_text(size = txt_pt2),
  axis.text   = element_text(size = txt_pt1)
)

line_theme <- theme(
  axis.line.x  = element_line(size = ln_pt, color = ln_col),
  axis.line.y  = element_line(size = ln_pt, color = ln_col),
  axis.ticks.x = element_line(size = ln_pt, color = ln_col),
  axis.ticks.y = element_line(size = ln_pt, color = ln_col)
)

base_theme <- theme_cowplot() +
  theme(
    plot.title       = element_text(face = "plain", size = ttl_pt2),
    strip.background = element_blank(),
    strip.text       = element_text(face = "plain")
  ) +
  txt_theme_1 +
  line_theme

umap_theme <- base_theme +
  theme(
    axis.title   = element_blank(),
    axis.line.x  = element_blank(),
    axis.line.y  = element_blank(),
    axis.ticks.x = element_blank(),
    axis.ticks.y = element_blank(),
    axis.text    = element_blank(),
    aspect.ratio = 0.9
  )

box_theme <- base_theme +
  theme(
    legend.position = "none",
    axis.line.x     = element_blank(),
    axis.line.y     = element_blank(),
    panel.border    = element_rect(fill = NA, color = ln_col, size = ln_pt),
    axis.text.x     = element_text(angle = 45, hjust = 1),
    axis.title.x    = element_blank()
  )

fade_0 <- "#FAFAFA"
fade_1 <- "#F0F0F0"
fade_2 <- "#D9D9D9"

hist_y_lab <- "number of cells"

# alpha for plots
al <- 0.7

# Okabe Ito color palettes
ito_cols <- c(
  palette_OkabeIto[c(1:3, 5)], "#D7301F",
  palette_OkabeIto[c(4, 6)],   "#6A51A3",
  palette_OkabeIto[7],         "#875C04",
  "#065D43", "#FFD6AD", "#00446E"
)

ito_cols <- ito_cols[3:length(ito_cols)] %>%
  darken(0.2) %>%
  c(ito_cols, ., "#686868", "#000000")

# Set sample colors
get_cols <- create_col_fun(ito_cols)

sam_cols <- c(
  "#00446E", "#0072B2", "#56B4E9",
  "#d7301f", "#D55E00", "#E69F00"
)

names(sam_cols) <- sam_lvls[params$samples]

# CHIKV treatment groups
chikv_infctd <- so_df %>%
  group_by(treatment) %>%
  summarize(mn = mean(nCount_CHIKV), .groups = "drop") %>%
  dplyr::filter(mn == max(mn)) %>%
  pull(treatment)

# Cell type colors
type_cols <- unique(so_df$cell_type)
type_cols <- set_names(ito_cols[seq_along(type_cols)], type_cols)

type_cols["unassigned"] <- "#999999"

subtype_cols <- c(colnames(ref_lec), colnames(ref_fib))
subtype_cols <- set_names(ito_cols[seq_along(subtype_cols)], subtype_cols)
subtype_cols["unassigned"] <- "#999999"
subtype_cols["other"]      <- fade_0

# CHIKV clusters colors
grp_cols <- set_names(
  c("#56B4E9", "#0072B2"),
  chikv_grps
)

grp_rep_cols <- grp_cols %>% 
  imap(~ set_names(
    rep(.x, n_rep),
    str_c(.y, "-", 1:n_rep)
  )) %>%
  flatten_chr()

# CHIKV cell type colors
n_high <- so_df %>%
  dplyr::filter(chikv_grp == chikv_grps[2]) %>%
  nrow()

chikv_type_cols <- unique(so_df$cell_type)
chikv_type_cols <- chikv_type_cols[!chikv_type_cols %in% names(subtype_cols)]
chikv_type_cols <- chikv_type_cols[!chikv_type_cols %in% c(lec_cell_types, fib_cell_types)]

avail_cols <- ito_cols[!ito_cols %in% subtype_cols]

chikv_type_cols <- set_names(
  avail_cols[seq_along(chikv_type_cols)],
  chikv_type_cols
)

chikv_type_cols <- c(subtype_cols, chikv_type_cols)

chikv_type_cols[chikv_grps[1]] <- fade_2

# Macrophage cluster colors
mac_clst_cols <- so_mac[[mac_clst_clmn]] %>%
  pull(mac_clst_clmn) %>%
  unique() %>%
  as.numeric() %>%
  sort() %>%
  as.character()

mac_clst_cols <- set_names(
  ito_cols[seq_along(mac_clst_cols)],
  mac_clst_cols
)

# UMAP themes
mac_u_theme <- umap_theme +
  theme(
    aspect.ratio         = 0.7,
    legend.position      = "bottom",
    legend.justification = "center",
    legend.title         = element_blank()
  )

int_u_theme <- mac_u_theme +
  theme(aspect.ratio = 1)

# Mac subset colors
mac_typ_cols <- feat_lvls[!grepl("infiltrating$", feat_lvls)]

mac_typ_cols <- set_names(
  ito_cols[seq_along(mac_typ_cols)],
  mac_typ_cols
)

mac_typ_cols["infiltrating"] <- "#0072B2"

# New labels for Mac subsets
mac_typ_labs <- names(mac_typ_cols) %>%
  str_replace("_interstitial", "+") %>%
  str_replace("infiltrating", "Inflammatory") %>%
  str_replace(".+_lining", "Lining")

mac_typ_labs <- set_names(mac_typ_labs, names(mac_typ_cols))

names(mac_typ_cols) <- mac_typ_labs[names(mac_typ_cols)]

mac_typ_cols_2 <- mac_typ_cols
mac_typ_cols_2["unassigned"] <- "grey75"

```

```{r "functions"}

plot_examples <- function(so_in, gns, split = NULL, thm = NULL,
                          clrs = c("#56B4E9", "white", "red")) {
  gns %>%
    map(~ {
      res <- so_in %>%
        FetchData(c("UMAP_1", "UMAP_2", split, .x)) %>%
        arrange(!!sym(.x)) %>%
        
        ggplot(aes(UMAP_1, UMAP_2, fill = !!sym(.x))) +
        geom_point_trace(size = 0.7, stroke = 0.5) +
        scale_fill_gradientn(colours = clrs) +
        guides(fill = guide_colorbar(ticks = FALSE, barheight = unit(150, "pt"))) +
        ggtitle(.x)
      
      if (!is.null(thm)) res <- res + thm
      
      if (!is.null(split)) {
        res <- res +
          facet_wrap(as.formula(str_c("~ ", split)))
      }
      
      res +
        theme(
          plot.title      = element_text(hjust = 0.5, size = 24),
          legend.position = "right"
        )
    })
}

#' Fetch genes for the provided annotations
fetch_genes <- function(terms, mart) {
  att  <- c("ensembl_gene_id", "external_gene_name")
  names(terms) <- names(terms) %||% rep("go_parent_name", length(terms))
  names(terms)[names(terms) == ""] <- "go_parent_name"
  
  res <- terms %>%
    imap(~ {
      getBM(
        attributes = att,
        filters    = .y,
        values     = .x,
        mart       = mart
      ) %>%
        pull(external_gene_name)
    }) %>%
    reduce(c) %>%
    unique()
  
  res
}

```

```{r "load macrophage objects"}

so_int <- qread(file.path(so_dir, "so_int.qs"))

# Format culemann gene lists
# Cx3cr1 is tagged with TdTomato
feats <- culemann_genes %>%
  imap(~ {
    fts <- .x %>%
      dplyr::select(gene, cluster) %>%
      split(.$cluster) %>%
      map(pull, gene)
    
    fts <- fts[names(fts) %in% feat_key[[.y]]]
    fts <- fts[feat_key[[.y]]]
    
    fts %>%
      map(~ {
        .x[.x == "TdTomato"] <- "Cx3cr1"
        .x[.x %in% VariableFeatures(so_int)]
      })
  }) %>%
  flatten()

so_int@active.assay <- "RNA"

```

## Macrophages

The expression of FcR genes is shown below for macrophages from mock- and CHIKV-infected mice.

```{r "FcR macrophages", fig.width = 15, fig.height = 8}

# FcR genes to plot
gns <- c(
  "Trim21", "Cd247", "Fcgr2b", "Fcer1g",
  "Fcmr",   "Fcgr1", "Fcgr3",  "Fcamr",
  "Fcer2a", "Pigr",  "Fcgr4",  "Ms4a2",
  "Fcer1a"
)

gns <- gns[gns %in% rownames(so)]

chikv_clrs    <- grp_cols
chikv_clrs[1] <- lighten("#009E73", 0.2)

treat_clrs        <- chikv_clrs
names(treat_clrs) <- treats

create_example_plots <- function(so_in, gn, split = "chikv_clst_grp",
                                 clrs = treat_clrs, pt_size = 0.2,
                                 show_umap = TRUE) {
  d <- so_in %>%
    FetchData(c("UMAP_1", "UMAP_2", split, "rep", gn)) %>%
    mutate(!!sym(split) := fct_relevel(!!sym(split), names(clrs)))
  
  u <- d %>%
    plot_scatter(
      gn,
      plot_colors = c("#56B4E9", "white", "#6A51A3"),
      n_label = "corner",
      size    = pt_size
    ) +
    guides(color = guide_colorbar(title.position = "top", barheight = unit(6, "pt"), barwidth = unit(100, "pt"), ticks = FALSE)) +
    umap_theme +
    theme(
      legend.position = "top",
      legend.justification = "center",
      legend.title = element_text(size = 20)
    )
  
  bx <- d %>%
    ggplot(aes(rep, !!sym(gn), fill = !!sym(split))) +
    geom_boxplot(outlier.size = 0.25) +
    scale_fill_manual(values = clrs) +
    facet_wrap(as.formula(str_c("~ ", split))) +
    djvdj_theme() +
    theme(
      legend.position = "none",
      panel.border    = element_blank(),
      axis.line.y     = element_line(color = "grey85", size = 0.5),
      axis.title.x    = element_blank(),
      axis.text.x     = element_blank(),
      axis.ticks.x    = element_blank(),
      strip.clip      = "off"
    )
  
  if (!show_umap) {
    bx <- bx +
      ggtitle(gn)
    
    return(bx)
  }
  
  bx <- bx +
    theme(axis.title.y = element_blank())
  
  plot_grid(
    u, bx,
    align = "vh",
    axis  = "trbl",
    nrow = 1,
    rel_widths = c(1, 0.82)
  )
}

# Create boxplots and UMAPs
gn_boxes <- gns %>%
  map(~ {
    create_example_plots(
      so_int, .x,
      split = "treatment",
      clrs  = treat_clrs
    )
  })

plot_grid(
  plotlist = gn_boxes,
  align = "vh",
  axis  = "trbl",
  ncol  = 4
)

```

<br>

## Monocytes

The expression of FcR genes is shown below for monocytes from mock- and CHIKV-infected mice.

```{r "FcR monocytes", fig.width = 9, fig.height = 6}

# Create boxplots and UMAPs
gn_boxes <- gns %>%
  map(~ {
    create_example_plots(
      subset(so, cell_type == "Monocytes"),
      .x,
      split     = "treatment",
      clrs      = treat_clrs,
      show_umap = FALSE
    )
  })

plot_grid(
  plotlist = gn_boxes,
  align = "vh",
  axis  = "trbl",
  ncol  = 4
)

```

<br>

## CHIKV-high macrophages

The expression of FcR genes is shown below for CHIKV-low and CHIKV-high macrophages from CHIKV-infected mice.

```{r "FcR CHIKV-high", fig.width = 15, fig.height = 8}

# Create boxplots and UMAPs
gn_boxes <- gns %>%
  map(~ {
    create_example_plots(
      subset(so_int, treatment == "CHIKV"),
      .x,
      split = "chikv_clst_grp",
      clrs  = chikv_clrs
    )
  })

plot_grid(
  plotlist = gn_boxes,
  align = "vh",
  axis  = "trbl",
  ncol  = 4
)

```

